// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bjYblYW44AnWsLvl1HaqfzUUxalu2zw',
    appId: '1:888341347385:web:30bb54c92b8b4735b5e1e8',
    messagingSenderId: '888341347385',
    projectId: 'new-todo-edf23',
    authDomain: 'new-todo-edf23.firebaseapp.com',
    storageBucket: 'new-todo-edf23.firebasestorage.app',
    measurementId: 'G-14J587HH8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxPLiXgqCrP3bveOKa3Vu5r4G6H-7EbmQ',
    appId: '1:888341347385:android:971fe38ebd40c478b5e1e8',
    messagingSenderId: '888341347385',
    projectId: 'new-todo-edf23',
    storageBucket: 'new-todo-edf23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrx06DPlx1wgJ8eJNPFr2erg6dy8ko5NY',
    appId: '1:888341347385:ios:0f85831277b090acb5e1e8',
    messagingSenderId: '888341347385',
    projectId: 'new-todo-edf23',
    storageBucket: 'new-todo-edf23.firebasestorage.app',
    iosBundleId: 'com.example.newTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrx06DPlx1wgJ8eJNPFr2erg6dy8ko5NY',
    appId: '1:888341347385:ios:0f85831277b090acb5e1e8',
    messagingSenderId: '888341347385',
    projectId: 'new-todo-edf23',
    storageBucket: 'new-todo-edf23.firebasestorage.app',
    iosBundleId: 'com.example.newTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5bjYblYW44AnWsLvl1HaqfzUUxalu2zw',
    appId: '1:888341347385:web:80b17e34e20e29c9b5e1e8',
    messagingSenderId: '888341347385',
    projectId: 'new-todo-edf23',
    authDomain: 'new-todo-edf23.firebaseapp.com',
    storageBucket: 'new-todo-edf23.firebasestorage.app',
    measurementId: 'G-3VXQSGVZR4',
  );
}
